- name: dev
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: weather
          units: metric
          hour-format: 24h
          location: Montpellier, France
          
        - type: to-do
          title: To-do
          id: todo

    - size: full
      widgets:
        - type: search
          autofocus: true
          new-tab: true
          search-engine: google
          bangs:
            - title: YouTube
              shortcut: "!yt"
              url: https://www.youtube.com/results?search_query={QUERY}

          